name: update
on: 
    repository_dispatch:
    release:
    
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - run: npm ci
            - run: npm run do
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
